---
- name: This is a test yaml playbook - edit by six fans
  hosts: test
  gather_facts: no
  tasks:
  - name: Hello world 1
    command : echo "hello world 1"
  - name: Show ifconfig information
    shell: ifconfig | grep inet
    register: hello
  - name: Date
    command : date
