# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('memo', models.CharField(blank=True, max_length=128, null=True)),
                ('bind_hosts', models.ManyToManyField(blank=True, to='accounts.Host')),
            ],
            options={
                'verbose_name': 'HostGroups',
                'verbose_name_plural': 'HostGroups',
            },
        ),
    ]
