# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180115_0910'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HostGroups',
            new_name='HostGroup',
        ),
    ]
