# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180115_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host_user',
            name='user',
        ),
        migrations.RemoveField(
            model_name='host',
            name='category',
        ),
        migrations.RemoveField(
            model_name='host',
            name='supervisor',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Host_User',
        ),
    ]
