# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180115_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='create_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='update_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='visible',
            field=models.BooleanField(default='True'),
        ),
    ]
