# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180115_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
