# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=b'profile/%Y/%m/%d')),
            ],
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
