# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-11 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180201_0710'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eta', models.DateTimeField()),
                ('args', models.CharField(blank=True, max_length=200, null=True)),
                ('sid', models.CharField(blank=True, max_length=70, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('result', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
