# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-11 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_scheduledetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledetails',
            name='eta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
