# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-24 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180211_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='ip',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
