# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-25 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20180224_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=15)),
                ('location', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
