# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-25 07:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20180225_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostgroup',
            name='bind_users',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.HostUser'),
            preserve_default=False,
        ),
    ]
