# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-25 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_hostuser_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostuser',
            name='user',
        ),
    ]
