# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-25 07:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0022_remove_hostgroup_bind_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostuser',
            name='department',
        ),
        migrations.RemoveField(
            model_name='hostuser',
            name='name',
        ),
        migrations.AddField(
            model_name='hostuser',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.HostGroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostuser',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
