# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-04 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_asset_server'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'permissions': (('can_read_assets', '\u8bfb\u53d6\u8d44\u4ea7\u6743\u9650'), ('can_change_assets', '\u66f4\u6539\u8d44\u4ea7\u6743\u9650'), ('can_add_assets', '\u6dfb\u52a0\u8d44\u4ea7\u6743\u9650'), ('can_delete_assets', '\u5220\u9664\u8d44\u4ea7\u6743\u9650'))},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'permissions': (('can_read_server_assets', '\u8bfb\u53d6\u670d\u52a1\u5668\u8d44\u4ea7\u6743\u9650'), ('can_change_server_assets', '\u66f4\u6539\u670d\u52a1\u5668\u8d44\u4ea7\u6743\u9650'), ('can_add_server_assets', '\u6dfb\u52a0\u670d\u52a1\u5668\u8d44\u4ea7\u6743\u9650'), ('can_delete_server_assets', '\u5220\u9664\u670d\u52a1\u5668\u8d44\u4ea7\u6743\u9650'))},
        ),
    ]
