# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-05 04:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20180304_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='update_date',
        ),
    ]
