# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-05 04:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20180305_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='name',
        ),
    ]
